language: python
python:
    - "2.6"
    - "2.7"
    - "3.2"
    - "pypy"

notifications:
  email:
    - hanno@hannosch.eu

install:
    - python bootstrap.py -d
    - bin/buildout

script:
    - bin/test
